"""base models only

Revision ID: 08c62a9b1d8b
Revises: 
Create Date: 2025-09-25 12:00:05.384073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08c62a9b1d8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentos_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('criterios', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_segmentos_clientes_activo'), 'segmentos_clientes', ['activo'], unique=False)
    op.create_index(op.f('ix_segmentos_clientes_id'), 'segmentos_clientes', ['id'], unique=False)
    op.create_table('tipos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_cliente_activo'), 'tipos_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tipos_cliente_id'), 'tipos_cliente', ['id'], unique=False)
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('abreviatura', sa.String(length=5), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    op.create_table('zonas_geograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('coordenadas_poligono', sa.Text(), nullable=True),
    sa.Column('centro_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('centro_lng', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('radio_km', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_geograficas_activa'), 'zonas_geograficas', ['activa'], unique=False)
    op.create_index(op.f('ix_zonas_geograficas_id'), 'zonas_geograficas', ['id'], unique=False)
    op.create_table('alertas_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.String(length=10), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_stock_activa'), 'alertas_stock', ['activa'], unique=False)
    op.create_index(op.f('ix_alertas_stock_created_at'), 'alertas_stock', ['created_at'], unique=False)
    op.create_index(op.f('ix_alertas_stock_id'), 'alertas_stock', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_stock_prioridad'), 'alertas_stock', ['prioridad'], unique=False)
    op.create_index(op.f('ix_alertas_stock_producto_id'), 'alertas_stock', ['producto_id'], unique=False)
    op.create_table('asignaciones_segmento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=False),
    sa.Column('asignado_por_tipo', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_desasignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_segmento_activo'), 'asignaciones_segmento', ['activo'], unique=False)
    op.create_index(op.f('ix_asignaciones_segmento_cliente_id'), 'asignaciones_segmento', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_segmento_id'), 'asignaciones_segmento', ['id'], unique=False)
    op.create_index(op.f('ix_asignaciones_segmento_segmento_id'), 'asignaciones_segmento', ['segmento_id'], unique=False)
    op.create_table('contactos_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_contacto', sa.String(length=20), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('realizado_por', sa.Integer(), nullable=False),
    sa.Column('realizado_por_tipo', sa.String(length=20), nullable=False),
    sa.Column('respuesta_cliente', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_realizada', sa.DateTime(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('notas_adicionales', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_clientes_cliente_id'), 'contactos_clientes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_created_at'), 'contactos_clientes', ['created_at'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_fecha_programada'), 'contactos_clientes', ['fecha_programada'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_fecha_realizada'), 'contactos_clientes', ['fecha_realizada'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_id'), 'contactos_clientes', ['id'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_resultado'), 'contactos_clientes', ['resultado'], unique=False)
    op.create_index(op.f('ix_contactos_clientes_tipo_contacto'), 'contactos_clientes', ['tipo_contacto'], unique=False)
    op.create_table('evaluaciones_crediticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evaluado_por', sa.Integer(), nullable=False),
    sa.Column('evaluado_por_tipo', sa.String(length=20), nullable=False),
    sa.Column('score_crediticio', sa.Integer(), nullable=False),
    sa.Column('limite_recomendado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('limite_anterior', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('factores_positivos', sa.Text(), nullable=True),
    sa.Column('factores_negativos', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('vigente_hasta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_crediticias_cliente_id'), 'evaluaciones_crediticias', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_crediticias_created_at'), 'evaluaciones_crediticias', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluaciones_crediticias_id'), 'evaluaciones_crediticias', ['id'], unique=False)
    op.create_table('historial_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('limite_anterior', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('limite_nuevo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credito_usado_anterior', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credito_usado_nuevo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('referencia_id', sa.String(length=100), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_tipo', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_credito_cliente_id'), 'historial_credito', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_historial_credito_created_at'), 'historial_credito', ['created_at'], unique=False)
    op.create_index(op.f('ix_historial_credito_id'), 'historial_credito', ['id'], unique=False)
    op.create_index(op.f('ix_historial_credito_tipo_movimiento'), 'historial_credito', ['tipo_movimiento'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_nuevo', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('referencia_id', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_created_at'), 'movimientos_stock', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_producto_id'), 'movimientos_stock', ['producto_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_tipo_movimiento'), 'movimientos_stock', ['tipo_movimiento'], unique=False)
    op.create_table('precios_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cliente_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento_volumen_1', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cantidad_minima_1', sa.Integer(), nullable=True),
    sa.Column('descuento_volumen_2', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cantidad_minima_2', sa.Integer(), nullable=True),
    sa.Column('descuento_volumen_3', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cantidad_minima_3', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_cliente_id'], ['tipos_cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'tipo_cliente_id', name='_producto_tipo_cliente_uc')
    )
    op.create_index(op.f('ix_precios_cliente_activo'), 'precios_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_precios_cliente_id'), 'precios_cliente', ['id'], unique=False)
    op.drop_table('evaluadores')
    op.drop_table('vendedores')
    op.drop_table('supervisores')
    op.drop_table('sesiones_activas')
    op.add_column('categorias', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('categorias', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('categorias', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('categorias_codigo_categoria_key', 'categorias', type_='unique')
    op.drop_constraint('categorias_nombre_key', 'categorias', type_='unique')
    op.create_index(op.f('ix_categorias_activo'), 'categorias', ['activo'], unique=False)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.drop_column('categorias', 'fecha_creacion')
    op.drop_column('categorias', 'orden_visualizacion')
    op.drop_column('categorias', 'categoria_id')
    op.drop_column('categorias', 'codigo_categoria')
    op.drop_column('categorias', 'activa')
    op.add_column('clientes', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('clientes', sa.Column('nombres', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('apellidos', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('direccion', sa.Text(), nullable=False))
    op.add_column('clientes', sa.Column('tipo_cliente_id', sa.Integer(), nullable=False))
    op.add_column('clientes', sa.Column('contacto_nombres', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('whatsapp', sa.String(length=15), nullable=True))
    op.add_column('clientes', sa.Column('limite_credito', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('clientes', sa.Column('credito_usado', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('clientes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clientes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('clientes', 'ruc',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('clientes', 'razon_social',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('clientes', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('clientes', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=11, scale=8),
               existing_nullable=True)
    op.drop_constraint('clientes_codigo_cliente_key', 'clientes', type_='unique')
    op.drop_constraint('clientes_ruc_key', 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_activo'), 'clientes', ['activo'], unique=False)
    op.create_index(op.f('ix_clientes_credito_usado'), 'clientes', ['credito_usado'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_latitud'), 'clientes', ['latitud'], unique=False)
    op.create_index(op.f('ix_clientes_limite_credito'), 'clientes', ['limite_credito'], unique=False)
    op.create_index(op.f('ix_clientes_longitud'), 'clientes', ['longitud'], unique=False)
    op.create_index(op.f('ix_clientes_ruc'), 'clientes', ['ruc'], unique=True)
    op.create_index(op.f('ix_clientes_tipo_cliente_id'), 'clientes', ['tipo_cliente_id'], unique=False)
    op.create_foreign_key(None, 'clientes', 'tipos_cliente', ['tipo_cliente_id'], ['id'])
    op.drop_column('clientes', 'configuraciones')
    op.drop_column('clientes', 'nombre_comercial')
    op.drop_column('clientes', 'distrito')
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'referencia')
    op.drop_column('clientes', 'cliente_id')
    op.drop_column('clientes', 'direccion_completa')
    op.drop_column('clientes', 'fecha_registro')
    op.drop_column('clientes', 'departamento')
    op.drop_column('clientes', 'fecha_modificacion')
    op.drop_column('clientes', 'codigo_cliente')
    op.drop_column('clientes', 'codigo_postal')
    op.drop_column('clientes', 'provincia')
    op.drop_column('clientes', 'precision_gps')
    op.drop_column('clientes', 'telefono')
    op.drop_column('clientes', 'metadatos')
    op.drop_column('clientes', 'verificado')
    op.drop_column('clientes', 'tipo_cliente')
    op.add_column('productos', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('productos', sa.Column('codigo', sa.String(length=20), nullable=False))
    op.add_column('productos', sa.Column('unidad_medida_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('precio_base', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('productos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('productos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('productos_codigo_barras_key', 'productos', type_='unique')
    op.drop_constraint('productos_codigo_producto_key', 'productos', type_='unique')
    op.create_index(op.f('ix_productos_activo'), 'productos', ['activo'], unique=False)
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_stock_actual'), 'productos', ['stock_actual'], unique=False)
    op.drop_constraint('productos_categoria_id_fkey', 'productos', type_='foreignkey')
    op.create_foreign_key(None, 'productos', 'categorias', ['categoria_id'], ['id'])
    op.create_foreign_key(None, 'productos', 'unidades_medida', ['unidad_medida_id'], ['id'])
    op.drop_column('productos', 'fecha_creacion')
    op.drop_column('productos', 'producto_id')
    op.drop_column('productos', 'precio_distribuidor')
    op.drop_column('productos', 'codigo_producto')
    op.drop_column('productos', 'imagen_url')
    op.drop_column('productos', 'precio_unitario')
    op.drop_column('productos', 'precio_mayorista')
    op.drop_column('productos', 'fecha_modificacion')
    op.drop_column('productos', 'destacado')
    op.drop_column('productos', 'codigo_barras')
    op.drop_column('productos', 'peso_unitario')
    op.drop_column('productos', 'unidad_medida')
    op.drop_column('productos', 'metadatos')
    op.drop_column('productos', 'volumen_unitario')
    op.drop_column('productos', 'especificaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('especificaciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('volumen_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('unidad_medida', sa.VARCHAR(length=20), server_default=sa.text("'unidad'::character varying"), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('peso_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('codigo_barras', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('destacado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('precio_mayorista', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('imagen_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('codigo_producto', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('precio_distribuidor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('producto_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('productos', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.create_foreign_key('productos_categoria_id_fkey', 'productos', 'categorias', ['categoria_id'], ['categoria_id'])
    op.drop_index(op.f('ix_productos_stock_actual'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_activo'), table_name='productos')
    op.create_unique_constraint('productos_codigo_producto_key', 'productos', ['codigo_producto'])
    op.create_unique_constraint('productos_codigo_barras_key', 'productos', ['codigo_barras'])
    op.drop_column('productos', 'updated_at')
    op.drop_column('productos', 'created_at')
    op.drop_column('productos', 'precio_base')
    op.drop_column('productos', 'unidad_medida_id')
    op.drop_column('productos', 'codigo')
    op.drop_column('productos', 'id')
    op.add_column('clientes', sa.Column('tipo_cliente', sa.VARCHAR(length=50), server_default=sa.text("'bodega'::character varying"), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('precision_gps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('codigo_postal', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('codigo_cliente', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('direccion_completa', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('cliente_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('clientes', sa.Column('referencia', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('distrito', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('nombre_comercial', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('configuraciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_tipo_cliente_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_ruc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_longitud'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_limite_credito'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_latitud'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_credito_usado'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_activo'), table_name='clientes')
    op.create_unique_constraint('clientes_ruc_key', 'clientes', ['ruc'])
    op.create_unique_constraint('clientes_codigo_cliente_key', 'clientes', ['codigo_cliente'])
    op.alter_column('clientes', 'longitud',
               existing_type=sa.DECIMAL(precision=11, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('clientes', 'latitud',
               existing_type=sa.DECIMAL(precision=10, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('clientes', 'razon_social',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('clientes', 'ruc',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.drop_column('clientes', 'updated_at')
    op.drop_column('clientes', 'created_at')
    op.drop_column('clientes', 'credito_usado')
    op.drop_column('clientes', 'limite_credito')
    op.drop_column('clientes', 'whatsapp')
    op.drop_column('clientes', 'contacto_nombres')
    op.drop_column('clientes', 'tipo_cliente_id')
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'apellidos')
    op.drop_column('clientes', 'nombres')
    op.drop_column('clientes', 'id')
    op.add_column('categorias', sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('categorias', sa.Column('codigo_categoria', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('categoria_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('categorias', sa.Column('orden_visualizacion', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('categorias', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_activo'), table_name='categorias')
    op.create_unique_constraint('categorias_nombre_key', 'categorias', ['nombre'])
    op.create_unique_constraint('categorias_codigo_categoria_key', 'categorias', ['codigo_categoria'])
    op.drop_column('categorias', 'created_at')
    op.drop_column('categorias', 'activo')
    op.drop_column('categorias', 'id')
    op.create_table('sesiones_activas',
    sa.Column('sesion_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evaluador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_usuario', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('token_acceso', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('ip_origen', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_expiracion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ultima_actividad', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('dispositivo_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['evaluadores.evaluador_id'], name='sesiones_activas_evaluador_id_fkey'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisores.supervisor_id'], name='sesiones_activas_supervisor_id_fkey'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.vendedor_id'], name='sesiones_activas_vendedor_id_fkey'),
    sa.PrimaryKeyConstraint('sesion_id', name='sesiones_activas_pkey')
    )
    op.create_table('supervisores',
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('codigo_supervisor', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nivel_acceso', sa.VARCHAR(length=20), server_default=sa.text("'supervisor'::character varying"), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_fcm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ultima_conexion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('configuraciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('supervisor_id', name='supervisores_pkey'),
    sa.UniqueConstraint('codigo_supervisor', name='supervisores_codigo_supervisor_key'),
    sa.UniqueConstraint('dni', name='supervisores_dni_key'),
    sa.UniqueConstraint('email', name='supervisores_email_key')
    )
    op.create_table('vendedores',
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('codigo_vendedor', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('distrito', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_fcm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ultima_conexion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('latitud_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitud_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precision_gps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ultima_ubicacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('configuraciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vendedor_id', name='vendedores_pkey'),
    sa.UniqueConstraint('codigo_vendedor', name='vendedores_codigo_vendedor_key'),
    sa.UniqueConstraint('dni', name='vendedores_dni_key'),
    sa.UniqueConstraint('email', name='vendedores_email_key')
    )
    op.create_table('evaluadores',
    sa.Column('evaluador_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('codigo_evaluador', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('direccion_trabajo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('distrito_asignado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provincia_asignada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('departamento_asignado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_fcm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ultima_conexion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('latitud_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitud_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precision_gps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ultima_ubicacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('configuraciones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('areas_evaluacion', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('evaluador_id', name='evaluadores_pkey'),
    sa.UniqueConstraint('codigo_evaluador', name='evaluadores_codigo_evaluador_key'),
    sa.UniqueConstraint('dni', name='evaluadores_dni_key'),
    sa.UniqueConstraint('email', name='evaluadores_email_key')
    )
    op.drop_index(op.f('ix_precios_cliente_id'), table_name='precios_cliente')
    op.drop_index(op.f('ix_precios_cliente_activo'), table_name='precios_cliente')
    op.drop_table('precios_cliente')
    op.drop_index(op.f('ix_movimientos_stock_tipo_movimiento'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_producto_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_created_at'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_historial_credito_tipo_movimiento'), table_name='historial_credito')
    op.drop_index(op.f('ix_historial_credito_id'), table_name='historial_credito')
    op.drop_index(op.f('ix_historial_credito_created_at'), table_name='historial_credito')
    op.drop_index(op.f('ix_historial_credito_cliente_id'), table_name='historial_credito')
    op.drop_table('historial_credito')
    op.drop_index(op.f('ix_evaluaciones_crediticias_id'), table_name='evaluaciones_crediticias')
    op.drop_index(op.f('ix_evaluaciones_crediticias_created_at'), table_name='evaluaciones_crediticias')
    op.drop_index(op.f('ix_evaluaciones_crediticias_cliente_id'), table_name='evaluaciones_crediticias')
    op.drop_table('evaluaciones_crediticias')
    op.drop_index(op.f('ix_contactos_clientes_tipo_contacto'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_resultado'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_id'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_fecha_realizada'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_fecha_programada'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_created_at'), table_name='contactos_clientes')
    op.drop_index(op.f('ix_contactos_clientes_cliente_id'), table_name='contactos_clientes')
    op.drop_table('contactos_clientes')
    op.drop_index(op.f('ix_asignaciones_segmento_segmento_id'), table_name='asignaciones_segmento')
    op.drop_index(op.f('ix_asignaciones_segmento_id'), table_name='asignaciones_segmento')
    op.drop_index(op.f('ix_asignaciones_segmento_cliente_id'), table_name='asignaciones_segmento')
    op.drop_index(op.f('ix_asignaciones_segmento_activo'), table_name='asignaciones_segmento')
    op.drop_table('asignaciones_segmento')
    op.drop_index(op.f('ix_alertas_stock_producto_id'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_prioridad'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_id'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_created_at'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_activa'), table_name='alertas_stock')
    op.drop_table('alertas_stock')
    op.drop_index(op.f('ix_zonas_geograficas_id'), table_name='zonas_geograficas')
    op.drop_index(op.f('ix_zonas_geograficas_activa'), table_name='zonas_geograficas')
    op.drop_table('zonas_geograficas')
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_tipos_cliente_id'), table_name='tipos_cliente')
    op.drop_index(op.f('ix_tipos_cliente_activo'), table_name='tipos_cliente')
    op.drop_table('tipos_cliente')
    op.drop_index(op.f('ix_segmentos_clientes_id'), table_name='segmentos_clientes')
    op.drop_index(op.f('ix_segmentos_clientes_activo'), table_name='segmentos_clientes')
    op.drop_table('segmentos_clientes')
    # ### end Alembic commands ###
